
jobs:
  include:
    - name: backend
      language: python

      python:
        - "3.8"

      addons:
        - postgresql: "9.5"

      before_script:
        - createdb barcart
        - make migrate

      # install dependencies
      install:
        - make install-b

      # lint backend then test
      script:
        - make lint-b
        - make test

    - name: frontend
      language: node_js

      node_js:
        - "14"

      # install dependencies
      install:
        - cd frontend && npm ci && cd ..

      # lint frontend
      script:
        - make lint-f
