# Generated by Django 3.1.6 on 2021-03-10 22:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20210310_2113'),
    ]

    operations = [
        migrations.CreateModel(
            name='Drink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('instructions', models.TextField(blank=True, default='')),
            ],
        ),
        migrations.CreateModel(
            name='DrinkIngredient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.FloatField()),
                ('units', models.CharField(choices=[('oz', 'oz'), ('tsp', 'tsp'), ('tbsp', 'tbsp')], max_length=20)),
                ('drink', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.drink')),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.ingredient')),
            ],
            options={
                'unique_together': {('ingredient', 'drink')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='recipeingredient',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='recipeingredient',
            name='ingredient',
        ),
        migrations.RemoveField(
            model_name='recipeingredient',
            name='recipe',
        ),
        migrations.DeleteModel(
            name='Recipe',
        ),
        migrations.DeleteModel(
            name='RecipeIngredient',
        ),
        migrations.AddField(
            model_name='drink',
            name='ingredients',
            field=models.ManyToManyField(through='core.DrinkIngredient', to='core.Ingredient'),
        ),
    ]
