# Generated by Django 3.1.6 on 2021-03-13 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20210312_0336'),
    ]

    operations = [
        migrations.AddField(
            model_name='drink',
            name='popularity',
            field=models.FloatField(default=0),
        ),
    ]
